version: '3.8'
services:
  app:
    build: .
    container_name: kekhaibaohiem_app
    restart: always
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=matkhau123
      - DATA_DIR=/app/data
    volumes:
      - ./data:/app/data
